### PR TITLE
Update skypebot.py

### PR DESCRIPTION
**Pull request by PrinceShaji**

### CODE REVIEW

**Comment by zhovner** [comment]
Is it work today? Do you have skypekit?

**Comment by PrinceShaji** [comment]
Sorry for the late reply. It was just an edit in the code's comment. Nothing major.

**Comment by zhovner** [comment]
SkypeKit SDK was discontinued and shouldn't work nowadays.

**Comment by PrinceShaji** [comment]
I know. I was just going through your code about an year ago and made a simple edit. It's not a big deal.

**Pull request closed without merging**
